# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
notifications:
  email:
    - stadlmann@uni-goettingen.de
install:
  - R -e "install.packages('devtools')"
  - R -e 'devtools::install_deps(dep = T)'
  - R -e "install.packages('glogis')"
  - R -e 'install.packages("bamlss", repos="http://R-Forge.R-project.org")'

script:
- R CMD build .
- travis_wait R CMD check *tar.gz

