# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
notifications:
  email:
    - stadlmann@uni-goettingen.de
install:
  - R -e "install.packages('devtools')"
  - R -e 'devtools::install_deps(dep = T)'
  - R -e "install.packages('glogis')"

